<?php

const API_MAX_LIMIT = 10000;

const ERROR_CODE_FOUND = 302;
const ERROR_CODE_FORBIDDEN = 403;
const ERROR_CODE_NOT_FOUND = 404;
const ERROR_CODE_METHOD_NOT_ALLOWED = 405;
const ERROR_CODE_REQUEST_CONTENT_TO_LARGE = 413;
const ERROR_CODE_SERVER_TOO_MANY_REQUESTS = 429;
const ERROR_CODE_INTRENAL_SERVER_ERROR = 500;
const ERROR_CODE_SERVER_OFF = 503;
const ERROR_CODE_AUTH = 53;
const ERROR_CODE_RIGHTS = 54;
const ERROR_CODE_AUTH_TPA = 55;
const ERROR_CODE_REQUEST_NAME = 1000;
const ERROR_CODE_SERVICE = 1001;
const ERROR_CODE_OPERATOR = 1002;
const ERROR_CODE_METHOD = 1003;
const ERROR_CODE_API_VERSION = 1004;
const ERROR_CODE_REQUEST_DATA = 2000;
const ERROR_CODE_REQUEST_REQUIRED = 2001;
const ERROR_CODE_REQUEST_TYPE = 2002;
const ERROR_CODE_REQUEST_VALUE = 2003;
const ERROR_CODE_REQUEST_FILTER = 2004;
const ERROR_CODE_REQUEST_PAGING = 2005;
const ERROR_CODE_REQUEST_ORDER = 2006;
const ERROR_CODE_NOT_ENOUGH_MONEY = 3000;
const ERROR_CODE_REQUIRED_PAYMENT = 3001;
const ERROR_CODE_NOT_ENOUGH_MONEY_OWNER = 3002;
