services:
  app:
    image: ghcr.io/sedm1/aiphra-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aiphra-backend-app
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      - aiphra-net
    env_file:
      - .env

  nginx:
    image: nginx:1.27-alpine
    container_name: aiphra-backend-nginx
    depends_on:
      - app
    restart: unless-stopped
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - "8080"
    networks:
      - aiphra-net

networks:
  aiphra-net:
    external: true
